codecov:
  require_ci_to_pass: true
coverage:
  status:
    patch:
      default:
        target: 50%
        branches:
          - "!hotfix"
    project:
      default:
        target: auto
        branches:
          - "!hotfix"